almoco = [
    {
        "nome": "Peito de frango grelhado (sem pele)",
        "energia_kcal": 165,
        "proteina_g": 31.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 3.6,
        "agua_g": 65,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 13,
        "potassio_mg": 256,
        "calcio_mg": 15,
        "ferro_mg": 1.0,
        "alergias": [],
        "descricao": "Proteína magra que ajuda no crescimento e recuperação. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Bife de vaca grelhado",
        "energia_kcal": 271,
        "proteina_g": 25.8,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 19.0,
        "agua_g": 55,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 318,
        "calcio_mg": 18,
        "ferro_mg": 2.6,
        "alergias": [],
        "descricao": "Rico em proteína e ferro — bom ocasionalmente. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Bife de porco grelhado",
        "energia_kcal": 242,
        "proteina_g": 27.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 14.0,
        "agua_g": 60,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 2,
        "potassio_mg": 330,
        "calcio_mg": 11,
        "ferro_mg": 1.0,
        "alergias": [],
        "descricao": "Saboroso e proteico — bom em refeições, mas moderar gorduras. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Peito de peru assado",
        "energia_kcal": 135,
        "proteina_g": 29.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 1.2,
        "agua_g": 69,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 5,
        "potassio_mg": 239,
        "calcio_mg": 11,
        "ferro_mg": 1.0,
        "alergias": [],
        "descricao": "Carne magra, ótima para sandes e almoço escolar. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Salmão grelhado",
        "energia_kcal": 208,
        "proteina_g": 20.4,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 13.4,
        "agua_g": 64,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 40,
        "potassio_mg": 363,
        "calcio_mg": 12,
        "ferro_mg": 0.5,
        "alergias": ["PEIXES"],
        "descricao": "Rico em ómega-3 — ótimo para o cérebro e coração. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Truta grelhada",
        "energia_kcal": 148,
        "proteina_g": 20.8,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 6.5,
        "agua_g": 72,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 50,
        "potassio_mg": 350,
        "calcio_mg": 40,
        "ferro_mg": 1.0,
        "alergias": ["PEIXES"],
        "descricao": "Peixe magro com ómega-3 — bom para crescimento e saúde. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Bacalhau cozido",
        "energia_kcal": 82,
        "proteina_g": 18.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 0.7,
        "agua_g": 79,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 2,
        "potassio_mg": 300,
        "calcio_mg": 18,
        "ferro_mg": 0.3,
        "alergias": ["PEIXES"],
        "descricao": "Magro e proteico — boa escolha para refeições equilibradas. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Lombinho de bacalhau salgado (dessalgado)",
        "energia_kcal": 290,
        "proteina_g": 62.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 2.5,
        "agua_g": 33,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 10,
        "potassio_mg": 800,
        "calcio_mg": 40,
        "ferro_mg": 1.6,
        "alergias": ["PEIXES"],
        "descricao": "Muito proteico, mas cuidado com o sal. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Atum enlatado (em água, escorrido)",
        "energia_kcal": 116,
        "proteina_g": 26.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 0.8,
        "agua_g": 72,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 5,
        "potassio_mg": 237,
        "calcio_mg": 10,
        "ferro_mg": 1.0,
        "alergias": ["PEIXES"],
        "descricao": "Prático e proteico — bom em saladas e sandes. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Sardinha enlatada em óleo",
        "energia_kcal": 208,
        "proteina_g": 25.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 11.5,
        "agua_g": 60,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 80,
        "potassio_mg": 490,
        "calcio_mg": 382,
        "ferro_mg": 2.9,
        "alergias": ["PEIXES"],
        "descricao": "Cheia de cálcio e ómega-3, especialmente se comer com ossos. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Camarão cozido",
        "energia_kcal": 99,
        "proteina_g": 24.0,
        "hidratos_g": 0.2,
        "acucares_g": 0.0,
        "lipidos_g": 0.3,
        "agua_g": 73,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 20,
        "potassio_mg": 264,
        "calcio_mg": 70,
        "ferro_mg": 0.3,
        "alergias": ["CRUSTACEOS"],
        "descricao": "Proteína magra e saborosa — cuidado se for salgado. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Carne picada (vacuno, cozida, magra)",
        "energia_kcal": 250,
        "proteina_g": 26.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 15.0,
        "agua_g": 58,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 330,
        "calcio_mg": 12,
        "ferro_mg": 2.6,
        "alergias": [],
        "descricao": "Base versátil para pratos — boa fonte de proteína. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Quibe assado (carne e bulgur)",
        "energia_kcal": 220,
        "proteina_g": 14.0,
        "hidratos_g": 20.0,
        "acucares_g": 1.0,
        "lipidos_g": 10.0,
        "agua_g": 45,
        "vitamina_c_mg": 2.0,
        "vitamina_a_ug": 30,
        "potassio_mg": 220,
        "calcio_mg": 30,
        "ferro_mg": 2.1,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Sabor tradicional — moderar por causa da gordura. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Falafel (sem tahine)",
        "energia_kcal": 333,
        "proteina_g": 13.0,
        "hidratos_g": 31.0,
        "acucares_g": 2.0,
        "lipidos_g": 15.0,
        "agua_g": 20,
        "vitamina_c_mg": 2.5,
        "vitamina_a_ug": 10,
        "potassio_mg": 420,
        "calcio_mg": 70,
        "ferro_mg": 3.0,
        "alergias": [],
        "descricao": "Bolinhos crocantes de grão — cheios de proteína vegetal. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Hambúrguer de leguminosas",
        "energia_kcal": 250,
        "proteina_g": 12.0,
        "hidratos_g": 30.0,
        "acucares_g": 3.0,
        "lipidos_g": 10.0,
        "agua_g": 55,
        "vitamina_c_mg": 3,
        "vitamina_a_ug": 5,
        "potassio_mg": 350,
        "calcio_mg": 40,
        "ferro_mg": 2.5,
        "alergias": [],
        "descricao": "Hambúrguer vegetal — boa proteína e fibra. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Tofu firme",
        "energia_kcal": 76,
        "proteina_g": 8.0,
        "hidratos_g": 1.9,
        "acucares_g": 0.3,
        "lipidos_g": 4.8,
        "agua_g": 85,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 121,
        "calcio_mg": 350,
        "ferro_mg": 2.7,
        "alergias": ["SOJA"],
        "descricao": "Alternativa proteica vegetal — absorve bem sabores. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Tofu fumado",
        "energia_kcal": 120,
        "proteina_g": 12.0,
        "hidratos_g": 2.0,
        "acucares_g": 0.5,
        "lipidos_g": 6.5,
        "agua_g": 70,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 140,
        "calcio_mg": 200,
        "ferro_mg": 2.0,
        "alergias": ["SOJA"],
        "descricao": "Alternativa vegetal saborosa e proteica — ótima em pratos quentes. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Tempeh",
        "energia_kcal": 193,
        "proteina_g": 19.0,
        "hidratos_g": 9.4,
        "acucares_g": 0.5,
        "lipidos_g": 10.8,
        "agua_g": 56,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 412,
        "calcio_mg": 111,
        "ferro_mg": 2.7,
        "alergias": ["SOJA"],
        "descricao": "Fermentado e proteico — forte sabor, ótimo em grelhados. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Quinoa cozida",
        "energia_kcal": 120,
        "proteina_g": 4.4,
        "hidratos_g": 21.3,
        "acucares_g": 0.9,
        "lipidos_g": 1.9,
        "agua_g": 71,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 172,
        "calcio_mg": 17,
        "ferro_mg": 1.5,
        "alergias": [],
        "descricao": "Pseudo-cereal proteico e leve — ideal em saladas. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Arroz integral cozido",
        "energia_kcal": 123,
        "proteina_g": 2.7,
        "hidratos_g": 25.6,
        "acucares_g": 0.2,
        "lipidos_g": 1.0,
        "agua_g": 70,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 86,
        "calcio_mg": 3,
        "ferro_mg": 0.6,
        "alergias": [],
        "descricao": "Mais fibra e nutrientes do que o branco — escolha inteligente. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Arroz branco cozido",
        "energia_kcal": 130,
        "proteina_g": 2.4,
        "hidratos_g": 28.0,
        "acucares_g": 0.1,
        "lipidos_g": 0.3,
        "agua_g": 68,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 35,
        "calcio_mg": 10,
        "ferro_mg": 0.2,
        "alergias": [],
        "descricao": "Acompanhamento clássico; menos fibra que o integral. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Massa cozida (trigo)",
        "energia_kcal": 131,
        "proteina_g": 5.0,
        "hidratos_g": 25.0,
        "acucares_g": 0.6,
        "lipidos_g": 1.1,
        "agua_g": 62,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 44,
        "calcio_mg": 7,
        "ferro_mg": 0.7,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Confort food versátil — bom em porções controladas. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Polenta cozida",
        "energia_kcal": 70,
        "proteina_g": 2.0,
        "hidratos_g": 15.0,
        "acucares_g": 0.2,
        "lipidos_g": 0.4,
        "agua_g": 82,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 30,
        "calcio_mg": 5,
        "ferro_mg": 0.4,
        "alergias": [],
        "descricao": "Versátil e leve — boa base para outros ingredientes. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Puré de batata",
        "energia_kcal": 88,
        "proteina_g": 1.6,
        "hidratos_g": 20.1,
        "acucares_g": 0.8,
        "lipidos_g": 0.2,
        "agua_g": 78,
        "vitamina_c_mg": 19.7,
        "vitamina_a_ug": 2,
        "potassio_mg": 379,
        "calcio_mg": 10,
        "ferro_mg": 0.3,
        "alergias": [],
        "descricao": "Clássico e confortável — bom acompanhamento, mas porções controladas. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Batata doce assada",
        "energia_kcal": 86,
        "proteina_g": 1.6,
        "hidratos_g": 20.1,
        "acucares_g": 4.2,
        "lipidos_g": 0.1,
        "agua_g": 77,
        "vitamina_c_mg": 2.4,
        "vitamina_a_ug": 709,
        "potassio_mg": 337,
        "calcio_mg": 30,
        "ferro_mg": 0.6,
        "alergias": [],
        "descricao": "Rica em vitamina A — ótima e saborosa alternativa ao puré. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Feijão cozido (feijão preto)",
        "energia_kcal": 132,
        "proteina_g": 8.9,
        "hidratos_g": 23.7,
        "acucares_g": 0.3,
        "lipidos_g": 0.5,
        "agua_g": 66,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 355,
        "calcio_mg": 27,
        "ferro_mg": 2.1,
        "alergias": [],
        "descricao": "Rico em fibra e proteína vegetal — ótimo para saciar. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Lentilhas cozidas",
        "energia_kcal": 116,
        "proteina_g": 9.0,
        "hidratos_g": 20.0,
        "acucares_g": 1.8,
        "lipidos_g": 0.4,
        "agua_g": 69,
        "vitamina_c_mg": 1.7,
        "vitamina_a_ug": 0,
        "potassio_mg": 369,
        "calcio_mg": 19,
        "ferro_mg": 3.3,
        "alergias": [],
        "descricao": "Grande fonte de proteína vegetal e ferro — ideal em sopas e saladas. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Grão-de-bico cozido",
        "energia_kcal": 164,
        "proteina_g": 8.9,
        "hidratos_g": 27.4,
        "acucares_g": 4.8,
        "lipidos_g": 2.6,
        "agua_g": 60,
        "vitamina_c_mg": 1.3,
        "vitamina_a_ug": 2,
        "potassio_mg": 291,
        "calcio_mg": 49,
        "ferro_mg": 2.9,
        "alergias": [],
        "descricao": "Versátil e cheio de fibra — bom em hummus e falafel. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Húmus (com tahine)",
        "energia_kcal": 166,
        "proteina_g": 7.9,
        "hidratos_g": 14.3,
        "acucares_g": 0.3,
        "lipidos_g": 9.6,
        "agua_g": 56,
        "vitamina_c_mg": 0.5,
        "vitamina_a_ug": 0,
        "potassio_mg": 228,
        "calcio_mg": 49,
        "ferro_mg": 2.4,
        "alergias": ["SEMENTES_SESAMO"],
        "descricao": "Cremoso e cheio de proteína do grão — ótimo com vegetais. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Molho de tomate (caseiro)",
        "energia_kcal": 29,
        "proteina_g": 1.4,
        "hidratos_g": 4.2,
        "acucares_g": 3.2,
        "lipidos_g": 0.2,
        "agua_g": 94,
        "vitamina_c_mg": 14.0,
        "vitamina_a_ug": 42,
        "potassio_mg": 237,
        "calcio_mg": 18,
        "ferro_mg": 0.5,
        "alergias": [],
        "descricao": "Base leve para pizzas e massas — saboroso e pouco calórico. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Salada de folhas (mix)",
        "energia_kcal": 20,
        "proteina_g": 1.8,
        "hidratos_g": 3.6,
        "acucares_g": 0.8,
        "lipidos_g": 0.3,
        "agua_g": 94,
        "vitamina_c_mg": 8.0,
        "vitamina_a_ug": 280,
        "potassio_mg": 210,
        "calcio_mg": 40,
        "ferro_mg": 1.0,
        "alergias": [],
        "descricao": "Mistura leve e cheia de vitaminas — tops para acompanhar refeições. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Brócolos cozidos",
        "energia_kcal": 35,
        "proteina_g": 2.8,
        "hidratos_g": 7.2,
        "acucares_g": 1.7,
        "lipidos_g": 0.4,
        "agua_g": 89,
        "vitamina_c_mg": 89.2,
        "vitamina_a_ug": 31,
        "potassio_mg": 316,
        "calcio_mg": 47,
        "ferro_mg": 0.7,
        "alergias": [],
        "descricao": "Vegetal poderoso em vitaminas e fibra — ótimo para crescer saudável. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Espinafres cozidos",
        "energia_kcal": 23,
        "proteina_g": 2.9,
        "hidratos_g": 3.6,
        "acucares_g": 0.4,
        "lipidos_g": 0.4,
        "agua_g": 91,
        "vitamina_c_mg": 28.1,
        "vitamina_a_ug": 469,
        "potassio_mg": 558,
        "calcio_mg": 99,
        "ferro_mg": 2.7,
        "alergias": [],
        "descricao": "Cheio de ferro e cálcio — ajuda a manter-te forte. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Cenoura crua",
        "energia_kcal": 41,
        "proteina_g": 0.9,
        "hidratos_g": 10,
        "acucares_g": 4.7,
        "lipidos_g": 0.2,
        "agua_g": 88,
        "vitamina_c_mg": 5.9,
        "vitamina_a_ug": 835,
        "potassio_mg": 320,
        "calcio_mg": 33,
        "ferro_mg": 0.3,
        "alergias": [],
        "descricao": "Crocrante e cheio de betacaroteno — ótimo para snacks saudáveis. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Tomate (cru)",
        "energia_kcal": 18,
        "proteina_g": 0.9,
        "hidratos_g": 3.9,
        "acucares_g": 2.6,
        "lipidos_g": 0.2,
        "agua_g": 94,
        "vitamina_c_mg": 13.7,
        "vitamina_a_ug": 42,
        "potassio_mg": 237,
        "calcio_mg": 10,
        "ferro_mg": 0.3,
        "alergias": [],
        "descricao": "Versátil e cheio de licopeno — ótimo cru ou cozido. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Tomate cherry",
        "energia_kcal": 18,
        "proteina_g": 0.9,
        "hidratos_g": 3.9,
        "acucares_g": 2.6,
        "lipidos_g": 0.2,
        "agua_g": 94,
        "vitamina_c_mg": 13.7,
        "vitamina_a_ug": 42,
        "potassio_mg": 237,
        "calcio_mg": 10,
        "ferro_mg": 0.3,
        "alergias": [],
        "descricao": "Pequenos e saborosos — perfeitos como petisco. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Pepino",
        "energia_kcal": 16,
        "proteina_g": 0.7,
        "hidratos_g": 3.6,
        "acucares_g": 1.7,
        "lipidos_g": 0.1,
        "agua_g": 95,
        "vitamina_c_mg": 2.8,
        "vitamina_a_ug": 2,
        "potassio_mg": 147,
        "calcio_mg": 16,
        "ferro_mg": 0.3,
        "alergias": [],
        "descricao": "Super hidratante e leve — bom em saladas. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Berinjela grelhada",
        "energia_kcal": 25,
        "proteina_g": 1.0,
        "hidratos_g": 6.0,
        "acucares_g": 3.2,
        "lipidos_g": 0.2,
        "agua_g": 92,
        "vitamina_c_mg": 2.2,
        "vitamina_a_ug": 0,
        "potassio_mg": 229,
        "calcio_mg": 9,
        "ferro_mg": 0.2,
        "alergias": [],
        "descricao": "Textura carnosa ótima para grelhar — bom substituto em pratos. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Curgete grelhada",
        "energia_kcal": 17,
        "proteina_g": 1.2,
        "hidratos_g": 3.1,
        "acucares_g": 2.5,
        "lipidos_g": 0.3,
        "agua_g": 94,
        "vitamina_c_mg": 17.9,
        "vitamina_a_ug": 7,
        "potassio_mg": 261,
        "calcio_mg": 16,
        "ferro_mg": 0.4,
        "alergias": [],
        "descricao": "Leve e hidratante — ótimo acompanhamento saudável. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Cogumelos (champignon, cozidos)",
        "energia_kcal": 22,
        "proteina_g": 3.1,
        "hidratos_g": 3.3,
        "acucares_g": 2.0,
        "lipidos_g": 0.3,
        "agua_g": 92,
        "vitamina_c_mg": 2.1,
        "vitamina_a_ug": 0,
        "potassio_mg": 318,
        "calcio_mg": 3,
        "ferro_mg": 0.5,
        "alergias": [],
        "descricao": "Sabor umami, baixo em calorias — bom em pizzas e tacos. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Ervilhas cozidas",
        "energia_kcal": 81,
        "proteina_g": 5.4,
        "hidratos_g": 14.5,
        "acucares_g": 5.7,
        "lipidos_g": 0.4,
        "agua_g": 79,
        "vitamina_c_mg": 40.0,
        "vitamina_a_ug": 64,
        "potassio_mg": 244,
        "calcio_mg": 25,
        "ferro_mg": 1.5,
        "alergias": [],
        "descricao": "Pequenas e cheias de proteína vegetal e fibra — ótimas no prato. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Milho cozido",
        "energia_kcal": 86,
        "proteina_g": 3.4,
        "hidratos_g": 19.0,
        "acucares_g": 6.3,
        "lipidos_g": 1.2,
        "agua_g": 70,
        "vitamina_c_mg": 6.8,
        "vitamina_a_ug": 9,
        "potassio_mg": 270,
        "calcio_mg": 2,
        "ferro_mg": 0.5,
        "alergias": [],
        "descricao": "Doce e crocante — bom acompanhamento ou snack. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Pão integral",
        "energia_kcal": 247,
        "proteina_g": 13,
        "hidratos_g": 41,
        "acucares_g": 5,
        "lipidos_g": 4.2,
        "agua_g": 35,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 230,
        "calcio_mg": 107,
        "ferro_mg": 3.6,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Mais fibra que o pão branco — bom para energia a longo prazo. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Pão de centeio",
        "energia_kcal": 259,
        "proteina_g": 9,
        "hidratos_g": 48,
        "acucares_g": 2,
        "lipidos_g": 3.3,
        "agua_g": 37,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 250,
        "calcio_mg": 40,
        "ferro_mg": 2.5,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Mais denso em fibra e com baixo índice glicémico — boa escolha. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Bagel integral com sementes",
        "energia_kcal": 270,
        "proteina_g": 10,
        "hidratos_g": 52,
        "acucares_g": 5,
        "lipidos_g": 3.0,
        "agua_g": 35,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 230,
        "calcio_mg": 80,
        "ferro_mg": 3.0,
        "alergias": ["TRIGO_GLUTEN", "SEMENTES_SESAMO"],
        "descricao": "Fibra e sementes — sacia bem e é nutritivo. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Pão pita",
        "energia_kcal": 275,
        "proteina_g": 9.0,
        "hidratos_g": 55.0,
        "acucares_g": 3.0,
        "lipidos_g": 1.5,
        "agua_g": 35,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 120,
        "calcio_mg": 80,
        "ferro_mg": 2.5,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Ótimo para wraps — prático e saboroso. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Queijo fresco (cottage)",
        "energia_kcal": 98,
        "proteina_g": 11.1,
        "hidratos_g": 3.4,
        "acucares_g": 2.7,
        "lipidos_g": 4.3,
        "agua_g": 79,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 27,
        "potassio_mg": 104,
        "calcio_mg": 83,
        "ferro_mg": 0.2,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Leve e proteico — ótimo em sandes e snacks. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Queijo mozzarella",
        "energia_kcal": 280,
        "proteina_g": 22.0,
        "hidratos_g": 2.2,
        "acucares_g": 1.0,
        "lipidos_g": 17.0,
        "agua_g": 51,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 360,
        "potassio_mg": 133,
        "calcio_mg": 505,
        "ferro_mg": 0.3,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Fresco e ótimo em pizzas e saladas — fonte de proteína. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Azeitonas (pretas)",
        "energia_kcal": 115,
        "proteina_g": 0.8,
        "hidratos_g": 6.3,
        "acucares_g": 0.5,
        "lipidos_g": 10.9,
        "agua_g": 78,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 3,
        "potassio_mg": 8,
        "calcio_mg": 52,
        "ferro_mg": 3.3,
        "alergias": [],
        "descricao": "Sabor intenso, fonte de gorduras monoinsaturadas — cuidado com o sal. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Azeite extra virgem",
        "energia_kcal": 884,
        "proteina_g": 0.0,
        "hidratos_g": 0.0,
        "acucares_g": 0.0,
        "lipidos_g": 100.0,
        "agua_g": 0,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 0,
        "calcio_mg": 0,
        "ferro_mg": 0.0,
        "alergias": [],
        "descricao": "Gordura saudável para temperar e cozinhar — usar com moderação. Aconselhável (verde) em pequenas quantidades.",
        "cor": "verde"
    },
    {
        "nome": "Húmus (com tahine)",
        "energia_kcal": 166,
        "proteina_g": 7.9,
        "hidratos_g": 14.3,
        "acucares_g": 0.3,
        "lipidos_g": 9.6,
        "agua_g": 56,
        "vitamina_c_mg": 0.5,
        "vitamina_a_ug": 0,
        "potassio_mg": 228,
        "calcio_mg": 49,
        "ferro_mg": 2.4,
        "alergias": ["SEMENTES_SESAMO"],
        "descricao": "Cremoso e cheio de proteína do grão — ótimo com vegetais. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Água",
        "energia_kcal": 0,
        "proteina_g": 0,
        "hidratos_g": 0,
        "acucares_g": 0,
        "lipidos_g": 0,
        "agua_g": 100,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 0,
        "calcio_mg": 0,
        "ferro_mg": 0,
        "alergias": [],
        "descricao": "Essencial para hidratação. Sem calorias nem nutrientes significativos. Aconselhável (verde).",
        "cor": "verde"
    }
]
