# almoco.py
almoco_nomes = [
    "Peito de frango grelhado (sem pele)",
    "Bife de vaca grelhado",
    "Bife de porco grelhado",
    "Peito de peru assado",
    "Salmão grelhado",
    "Truta grelhada",
    "Bacalhau cozido",
    "Lombinho de bacalhau salgado (dessalgado)",
    "Atum enlatado (em água, escorrido)",
    "Sardinha enlatada em óleo",
    "Camarão cozido",
    "Carne picada (vacuno, cozida, magra)",
    "Quibe assado (carne e bulgur)",
    "Falafel (sem tahine)",
    "Hambúrguer de leguminosas",
    "Tofu firme",
    "Tofu fumado",
    "Tempeh",
    "Quinoa cozida",
    "Arroz integral cozido",
    "Arroz branco cozido",
    "Massa cozida (trigo)",
    "Polenta cozida",
    "Puré de batata",
    "Batata doce assada",
    "Feijão cozido (feijão preto)",
    "Lentilhas cozidas",
    "Grão-de-bico cozido",
    "Húmus (com tahine)",
    "Molho de tomate (caseiro)",
    "Salada de folhas (mix)",
    "Brócolos cozidos",
    "Espinafres cozidos",
    "Cenoura crua",
    "Tomate (cru)",
    "Tomate cherry",
    "Pepino",
    "Berinjela grelhada",
    "Curgete grelhada",
    "Cogumelos (champignon, cozidos)",
    "Ervilhas cozidas",
    "Milho cozido",
    "Pão integral",
    "Pão de centeio",
    "Bagel integral com sementes",
    "Pão pita",
    "Queijo fresco (cottage)",
    "Queijo mozzarella",
    "Azeitonas (pretas)",
    "Azeite extra virgem",
    "Água"
]