pequeno_almoco = [
    {
        "nome": "Maçã",
        "energia_kcal": 52,
        "proteina_g": 0.3,
        "hidratos_g": 14,
        "acucares_g": 10,
        "lipidos_g": 0.2,
        "agua_g": 86,
        "vitamina_c_mg": 4.6,
        "vitamina_a_ug": 3,
        "potassio_mg": 107,
        "calcio_mg": 6,
        "ferro_mg": 0.1,
        "alergias": ["FRUTAS"],
        "descricao": "Crocrante e doce — ótimo snack para a escola. Aconselhável (verde): come regularmente!",
        "cor": "verde"
    },
    {
        "nome": "Banana",
        "energia_kcal": 89,
        "proteina_g": 1.1,
        "hidratos_g": 23,
        "acucares_g": 12,
        "lipidos_g": 0.3,
        "agua_g": 74,
        "vitamina_c_mg": 8.7,
        "vitamina_a_ug": 3,
        "potassio_mg": 358,
        "calcio_mg": 5,
        "ferro_mg": 0.3,
        "alergias": ["FRUTAS"],
        "descricao": "Perfeita para energia antes do treino. Aconselhável (verde): ótima diária.",
        "cor": "verde"
    },
    {
        "nome": "Laranja (fruta)",
        "energia_kcal": 47,
        "proteina_g": 0.9,
        "hidratos_g": 12,
        "acucares_g": 9,
        "lipidos_g": 0.1,
        "agua_g": 87,
        "vitamina_c_mg": 53.2,
        "vitamina_a_ug": 11,
        "potassio_mg": 181,
        "calcio_mg": 40,
        "ferro_mg": 0.1,
        "alergias": ["FRUTAS"],
        "descricao": "Suculenta e cheia de vitamina C — boa para a imunidade. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Sumo de laranja (natural)",
        "energia_kcal": 45,
        "proteina_g": 0.7,
        "hidratos_g": 10.4,
        "acucares_g": 8.4,
        "lipidos_g": 0.2,
        "agua_g": 88,
        "vitamina_c_mg": 50,
        "vitamina_a_ug": 11,
        "potassio_mg": 200,
        "calcio_mg": 11,
        "ferro_mg": 0.2,
        "alergias": ["FRUTAS"],
        "descricao": "Bebida fresca com vitamina C, mas tem açúcar natural. Com moderação — aconselhável com cautela (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Sumo de maçã (natural)",
        "energia_kcal": 46,
        "proteina_g": 0.1,
        "hidratos_g": 11.3,
        "acucares_g": 10.0,
        "lipidos_g": 0.1,
        "agua_g": 88,
        "vitamina_c_mg": 1,
        "vitamina_a_ug": 2,
        "potassio_mg": 100,
        "calcio_mg": 6,
        "ferro_mg": 0.1,
        "alergias": ["FRUTAS"],
        "descricao": "Doce e prático, mas com muitos açúcares. Melhor ocasionalmente — (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Morangos",
        "energia_kcal": 32,
        "proteina_g": 0.7,
        "hidratos_g": 7.7,
        "acucares_g": 4.9,
        "lipidos_g": 0.3,
        "agua_g": 91,
        "vitamina_c_mg": 58.8,
        "vitamina_a_ug": 1,
        "potassio_mg": 153,
        "calcio_mg": 16,
        "ferro_mg": 0.4,
        "alergias": ["FRUTAS"],
        "descricao": "Doces e ricos em vitamina C — snack fresco e saudável. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Framboesa",
        "energia_kcal": 52,
        "proteina_g": 1.2,
        "hidratos_g": 12,
        "acucares_g": 4.4,
        "lipidos_g": 0.7,
        "agua_g": 86,
        "vitamina_c_mg": 26.2,
        "vitamina_a_ug": 2,
        "potassio_mg": 151,
        "calcio_mg": 25,
        "ferro_mg": 0.7,
        "alergias": ["FRUTAS"],
        "descricao": "Pequenas e cheias de fibra — perfeitas para snacks ou iogurtes. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Kiwi",
        "energia_kcal": 61,
        "proteina_g": 1.1,
        "hidratos_g": 15,
        "acucares_g": 9,
        "lipidos_g": 0.5,
        "agua_g": 83,
        "vitamina_c_mg": 92.7,
        "vitamina_a_ug": 4,
        "potassio_mg": 312,
        "calcio_mg": 34,
        "ferro_mg": 0.3,
        "alergias": ["FRUTAS"],
        "descricao": "Pequeno e poderoso em vitamina C — ótimo para snacks. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Pera",
        "energia_kcal": 57,
        "proteina_g": 0.4,
        "hidratos_g": 15,
        "acucares_g": 10,
        "lipidos_g": 0.1,
        "agua_g": 84,
        "vitamina_c_mg": 4.3,
        "vitamina_a_ug": 1,
        "potassio_mg": 116,
        "calcio_mg": 9,
        "ferro_mg": 0.2,
        "alergias": ["FRUTAS"],
        "descricao": "Doce e hidratante — fácil de levar na mochila. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Leite integral",
        "energia_kcal": 61,
        "proteina_g": 3.2,
        "hidratos_g": 4.8,
        "acucares_g": 4.8,
        "lipidos_g": 3.3,
        "agua_g": 87,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 46,
        "potassio_mg": 150,
        "calcio_mg": 113,
        "ferro_mg": 0.0,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Bom para ossos e para o pequeno-almoço; contém gordura. Aconselhável com cautela (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Leite magro",
        "energia_kcal": 35,
        "proteina_g": 3.4,
        "hidratos_g": 5.0,
        "acucares_g": 5.0,
        "lipidos_g": 0.1,
        "agua_g": 91,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 5,
        "potassio_mg": 150,
        "calcio_mg": 125,
        "ferro_mg": 0.0,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Opção mais leve que ajuda a ganhar proteína sem tanta gordura. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Leite de amêndoa (sem açúcar, comercial)",
        "energia_kcal": 15,
        "proteina_g": 0.6,
        "hidratos_g": 0.3,
        "acucares_g": 0.2,
        "lipidos_g": 1.2,
        "agua_g": 97,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 50,
        "calcio_mg": 120,
        "ferro_mg": 0.2,
        "alergias": ["AMENDOA"],
        "descricao": "Bebida leve e saborosa; frequentemente fortificada. Aconselhável (verde) para variar o leite.",
        "cor": "verde"
    },
    {
        "nome": "Leite de soja (sem açúcar)",
        "energia_kcal": 33,
        "proteina_g": 3.3,
        "hidratos_g": 0.6,
        "acucares_g": 0.2,
        "lipidos_g": 1.6,
        "agua_g": 94,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 120,
        "calcio_mg": 25,
        "ferro_mg": 0.4,
        "alergias": ["SOJA"],
        "descricao": "Boa fonte de proteína vegetal e versátil. Aconselhável (verde) como alternativa.",
        "cor": "verde"
    },
    {
        "nome": "Iogurte natural (inteiro)",
        "energia_kcal": 61,
        "proteina_g": 3.5,
        "hidratos_g": 4.7,
        "acucares_g": 4.7,
        "lipidos_g": 3.3,
        "agua_g": 85,
        "vitamina_c_mg": 0.5,
        "vitamina_a_ug": 38,
        "potassio_mg": 141,
        "calcio_mg": 110,
        "ferro_mg": 0.1,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Cremoso e cheio de cálcio; bom snack. Aconselhável com cautela (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Iogurte grego (integral)",
        "energia_kcal": 120,
        "proteina_g": 10,
        "hidratos_g": 3.6,
        "acucares_g": 3.2,
        "lipidos_g": 7.0,
        "agua_g": 77,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 58,
        "potassio_mg": 141,
        "calcio_mg": 110,
        "ferro_mg": 0.1,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Muito proteico e saciante — ótimo depois do treino. Aconselhável com cautela (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Café preto (sem açúcar)",
        "energia_kcal": 1,
        "proteina_g": 0.1,
        "hidratos_g": 0,
        "acucares_g": 0,
        "lipidos_g": 0,
        "agua_g": 99,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 49,
        "calcio_mg": 4,
        "ferro_mg": 0.0,
        "alergias": [],
        "descricao": "Bebida energética por causa da cafeína — pouca caloria. Aconselhável (verde) com moderação para jovens.",
        "cor": "verde"
    },
    {
        "nome": "Chá preto (preparado)",
        "energia_kcal": 1,
        "proteina_g": 0,
        "hidratos_g": 0,
        "acucares_g": 0,
        "lipidos_g": 0,
        "agua_g": 99,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 10,
        "calcio_mg": 3,
        "ferro_mg": 0.0,
        "alergias": [],
        "descricao": "Quase sem calorias e reconfortante. Aconselhável (verde) sem açúcar.",
        "cor": "verde"
    },
    {
        "nome": "Café com leite",
        "energia_kcal": 40,
        "proteina_g": 3.2,
        "hidratos_g": 3.3,
        "acucares_g": 3.3,
        "lipidos_g": 1.5,
        "agua_g": 93,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 50,
        "potassio_mg": 120,
        "calcio_mg": 120,
        "ferro_mg": 0.0,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Bebida matinal comum — contém cafeína e leite. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Chocolate quente (com leite)",
        "energia_kcal": 83,
        "proteina_g": 3.0,
        "hidratos_g": 11.0,
        "acucares_g": 10.0,
        "lipidos_g": 2.5,
        "agua_g": 83,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 40,
        "potassio_mg": 150,
        "calcio_mg": 120,
        "ferro_mg": 0.3,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Aconchegante e doce — ótimo em dias frios, mas rico em açúcar. Pouco aconselhável (laranja).",
        "cor": "laranja"
    },
    {
        "nome": "Smoothie de morango (média)",
        "energia_kcal": 50,
        "proteina_g": 0.6,
        "hidratos_g": 12,
        "acucares_g": 9,
        "lipidos_g": 0.3,
        "agua_g": 86,
        "vitamina_c_mg": 30,
        "vitamina_a_ug": 5,
        "potassio_mg": 120,
        "calcio_mg": 15,
        "ferro_mg": 0.2,
        "alergias": ["FRUTAS"],
        "descricao": "Refrescante e cheio de vitamina C, mas cuidado com adição de açúcar. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Aveia (flocos, seca)",
        "energia_kcal": 389,
        "proteina_g": 16.9,
        "hidratos_g": 66.3,
        "acucares_g": 1.0,
        "lipidos_g": 6.9,
        "agua_g": 8,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 429,
        "calcio_mg": 54,
        "ferro_mg": 4.7,
        "alergias": [],
        "descricao": "Super versátil — papas, panquecas ou batidos. Aconselhável (verde) para o pequeno-almoço.",
        "cor": "verde"
    },
    {
        "nome": "Papas de aveia (cozidas)",
        "energia_kcal": 71,
        "proteina_g": 2.5,
        "hidratos_g": 12,
        "acucares_g": 0.5,
        "lipidos_g": 1.4,
        "agua_g": 84,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 63,
        "calcio_mg": 12,
        "ferro_mg": 0.9,
        "alergias": [],
        "descricao": "Quentes e saciantes — perfeitas com fruta. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Cereal instantâneo de aveia (preparado)",
        "energia_kcal": 80,
        "proteina_g": 2.5,
        "hidratos_g": 14,
        "acucares_g": 3,
        "lipidos_g": 1.5,
        "agua_g": 80,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 80,
        "calcio_mg": 10,
        "ferro_mg": 1.0,
        "alergias": [],
        "descricao": "Rápido e prático para manhãs ocupadas; verifica o açúcar adicionado. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Cereais flocos (cornflakes)",
        "energia_kcal": 357,
        "proteina_g": 7.5,
        "hidratos_g": 84,
        "acucares_g": 8.3,
        "lipidos_g": 0.4,
        "agua_g": 4,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 120,
        "calcio_mg": 4,
        "ferro_mg": 7.9,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Rápido e prático; muitas vezes tem açúcar e pouca fibra. Melhor com moderação — (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Granola (com FRUTAS secos e mel)",
        "energia_kcal": 471,
        "proteina_g": 10,
        "hidratos_g": 64,
        "acucares_g": 19,
        "lipidos_g": 20,
        "agua_g": 4,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 400,
        "calcio_mg": 60,
        "ferro_mg": 4.0,
        "alergias": ["AMENDOA", "NOZES", "AVELHA", "CASTANHA", "PISTACHIO", "TRIGO_GLUTEN"],
        "descricao": "Ótima saborosa e energética, mas calórica — come com moderação. Aconselhável com cautela (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Muesli (sem açúcar)",
        "energia_kcal": 350,
        "proteina_g": 9,
        "hidratos_g": 57,
        "acucares_g": 8,
        "lipidos_g": 6,
        "agua_g": 7,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 400,
        "calcio_mg": 50,
        "ferro_mg": 3.5,
        "alergias": ["AMENDOA", "NOZES", "AVELHA", "CASTANHA", "PISTACHIO"],
        "descricao": "Cereais pouco processados — ótimo com iogurte e fruta. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Pão integral",
        "energia_kcal": 247,
        "proteina_g": 13,
        "hidratos_g": 41,
        "acucares_g": 5,
        "lipidos_g": 4.2,
        "agua_g": 35,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 230,
        "calcio_mg": 107,
        "ferro_mg": 3.6,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Mais fibra que o pão branco — bom para energia a longo prazo. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Pão branco",
        "energia_kcal": 265,
        "proteina_g": 9,
        "hidratos_g": 49,
        "acucares_g": 5,
        "lipidos_g": 3.2,
        "agua_g": 36,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 115,
        "calcio_mg": 120,
        "ferro_mg": 3.3,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Rápida energia, mas menos fibra. Melhor com moderação — (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Bagel (simples)",
        "energia_kcal": 250,
        "proteina_g": 9,
        "hidratos_g": 49,
        "acucares_g": 4,
        "lipidos_g": 1.6,
        "agua_g": 38,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 115,
        "calcio_mg": 80,
        "ferro_mg": 2.5,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Pão denso e saboroso; bom para sandes, mas calórico. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Bagel integral com sementes",
        "energia_kcal": 270,
        "proteina_g": 10,
        "hidratos_g": 52,
        "acucares_g": 5,
        "lipidos_g": 3.0,
        "agua_g": 35,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 230,
        "calcio_mg": 80,
        "ferro_mg": 3.0,
        "alergias": ["TRIGO_GLUTEN", "SEMENTES_SESAMO"],
        "descricao": "Fibra e sementes — sacia bem e é nutritivo. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Croissant",
        "energia_kcal": 406,
        "proteina_g": 8,
        "hidratos_g": 45,
        "acucares_g": 7,
        "lipidos_g": 21,
        "agua_g": 24,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 35,
        "potassio_mg": 190,
        "calcio_mg": 23,
        "ferro_mg": 2.2,
        "alergias": ["TRIGO_GLUTEN", "LEITE_DERIVADOS"],
        "descricao": "Delícia folhada, mas calórico e gorduroso. Pouco aconselhável (laranja) — melhor só como mimo ocasional.",
        "cor": "laranja"
    },
    {
        "nome": "Torrada com tomate (preparado)",
        "energia_kcal": 150,
        "proteina_g": 4,
        "hidratos_g": 24,
        "acucares_g": 3,
        "lipidos_g": 3,
        "agua_g": 65,
        "vitamina_c_mg": 10,
        "vitamina_a_ug": 50,
        "potassio_mg": 200,
        "calcio_mg": 20,
        "ferro_mg": 1.1,
        "alergias": ["TRIGO_GLUTEN"],
        "descricao": "Leve e saborosa — ótima opção matinal. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Panquecas (cozidas, simples)",
        "energia_kcal": 227,
        "proteina_g": 6,
        "hidratos_g": 27,
        "acucares_g": 7,
        "lipidos_g": 9,
        "agua_g": 45,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 64,
        "potassio_mg": 120,
        "calcio_mg": 120,
        "ferro_mg": 1.2,
        "alergias": ["TRIGO_GLUTEN", "OVOS", "LEITE_DERIVADOS"],
        "descricao": "Delícia do brunch — sabor alto, valor calórico moderado. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Panqueca de aveia com banana",
        "energia_kcal": 180,
        "proteina_g": 5,
        "hidratos_g": 30,
        "acucares_g": 9,
        "lipidos_g": 4,
        "agua_g": 60,
        "vitamina_c_mg": 8,
        "vitamina_a_ug": 40,
        "potassio_mg": 300,
        "calcio_mg": 60,
        "ferro_mg": 1.2,
        "alergias": ["OVOS", "LEITE_DERIVADOS", "TRIGO_GLUTEN"],
        "descricao": "Versão mais saudável de panqueca — energia e fibra. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Crepe simples",
        "energia_kcal": 159,
        "proteina_g": 5,
        "hidratos_g": 27,
        "acucares_g": 3,
        "lipidos_g": 3.2,
        "agua_g": 55,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 50,
        "potassio_mg": 130,
        "calcio_mg": 60,
        "ferro_mg": 1.0,
        "alergias": ["OVOS", "LEITE_DERIVADOS", "TRIGO_GLUTEN"],
        "descricao": "Leve e versátil — serve para doces ou salgados. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Waffle",
        "energia_kcal": 291,
        "proteina_g": 6.0,
        "hidratos_g": 36.0,
        "acucares_g": 12.0,
        "lipidos_g": 13.0,
        "agua_g": 30,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 150,
        "potassio_mg": 140,
        "calcio_mg": 120,
        "ferro_mg": 2.5,
        "alergias": ["TRIGO_GLUTEN", "OVOS", "LEITE_DERIVADOS"],
        "descricao": "Doce e calórico — ótimo como guloseima ocasional. Pouco aconselhável (laranja).",
        "cor": "laranja"
    },
    {
        "nome": "Muffin de mirtilo",
        "energia_kcal": 377,
        "proteina_g": 6,
        "hidratos_g": 53,
        "acucares_g": 23,
        "lipidos_g": 15,
        "agua_g": 28,
        "vitamina_c_mg": 2,
        "vitamina_a_ug": 120,
        "potassio_mg": 130,
        "calcio_mg": 30,
        "ferro_mg": 2.2,
        "alergias": ["TRIGO_GLUTEN", "LEITE_DERIVADOS", "OVOS"],
        "descricao": "Doce e energético — bom como mimo ocasional. Pouco aconselhável (laranja).",
        "cor": "laranja"
    },
    {
        "nome": "Xarope de bordo (maple syrup)",
        "energia_kcal": 260,
        "proteina_g": 0,
        "hidratos_g": 67,
        "acucares_g": 60,
        "lipidos_g": 0,
        "agua_g": 35,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 20,
        "calcio_mg": 13,
        "ferro_mg": 0.1,
        "alergias": [],
        "descricao": "Doçura natural para panquecas, mas cheio de açúcar. Pouco aconselhável (laranja) — usa pouco.",
        "cor": "laranja"
    },
    {
        "nome": "Mel (apicultura)",
        "energia_kcal": 304,
        "proteina_g": 0.3,
        "hidratos_g": 82,
        "acucares_g": 82,
        "lipidos_g": 0,
        "agua_g": 17,
        "vitamina_c_mg": 0.5,
        "vitamina_a_ug": 0,
        "potassio_mg": 52,
        "calcio_mg": 6,
        "ferro_mg": 0.4,
        "alergias": [],
        "descricao": "Adoçante natural gostoso, mas muito calórico. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Manteiga (normal)",
        "energia_kcal": 717,
        "proteina_g": 0.9,
        "hidratos_g": 0.1,
        "acucares_g": 0.1,
        "lipidos_g": 81,
        "agua_g": 16,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 684,
        "potassio_mg": 24,
        "calcio_mg": 24,
        "ferro_mg": 0.0,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Muito calórica e gordurosa — sabor ótimo mas usar pouco. Pouco aconselhável (laranja).",
        "cor": "laranja"
    },
    {
        "nome": "Manteiga de amendoim (cremosa)",
        "energia_kcal": 588,
        "proteina_g": 25,
        "hidratos_g": 20,
        "acucares_g": 9,
        "lipidos_g": 50,
        "agua_g": 2.5,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 705,
        "calcio_mg": 43,
        "ferro_mg": 1.9,
        "alergias": ["AMENDOIM"],
        "descricao": "Cheia de proteína e gordura — sacia bem, mas é calórica. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Nozes (mistura: noz, amêndoa, avelã) — FRUTAS secos",
        "energia_kcal": 607,
        "proteina_g": 15,
        "hidratos_g": 13.7,
        "acucares_g": 4.4,
        "lipidos_g": 54,
        "agua_g": 4,
        "vitamina_c_mg": 0.7,
        "vitamina_a_ug": 0,
        "potassio_mg": 650,
        "calcio_mg": 140,
        "ferro_mg": 3.0,
        "alergias": ["NOZES", "AMENDOA", "AVELHA"],
        "descricao": "Super energéticas e cheias de gorduras saudáveis — pequenas porções. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Amêndoas cruas",
        "energia_kcal": 579,
        "proteina_g": 21.2,
        "hidratos_g": 21.6,
        "acucares_g": 4.4,
        "lipidos_g": 49.9,
        "agua_g": 5.3,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 733,
        "calcio_mg": 264,
        "ferro_mg": 3.7,
        "alergias": ["AMENDOA"],
        "descricao": "Densas em energia e gorduras boas — ideal em pequenas porções. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Amendoim torrado sem sal",
        "energia_kcal": 567,
        "proteina_g": 25.8,
        "hidratos_g": 16.1,
        "acucares_g": 4.7,
        "lipidos_g": 49.2,
        "agua_g": 2.2,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 0,
        "potassio_mg": 658,
        "calcio_mg": 92,
        "ferro_mg": 1.9,
        "alergias": ["AMENDOIM"],
        "descricao": "Rico em proteína e gorduras — bom snack, mas calórico. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Sementes de chia",
        "energia_kcal": 486,
        "proteina_g": 16.5,
        "hidratos_g": 42.1,
        "acucares_g": 0,
        "lipidos_g": 30.7,
        "agua_g": 6,
        "vitamina_c_mg": 1.6,
        "vitamina_a_ug": 0,
        "potassio_mg": 407,
        "calcio_mg": 631,
        "ferro_mg": 7.7,
        "alergias": ["OUTRAS_SEMENTES_OLEAGINOSAS"],
        "descricao": "Pequenas mas poderosas — fibra e ómega-3. Aconselhável (verde) em iogurtes ou batidos.",
        "cor": "verde"
    },
    {
        "nome": "Abacate",
        "energia_kcal": 160,
        "proteina_g": 2.0,
        "hidratos_g": 9,
        "acucares_g": 0.7,
        "lipidos_g": 15,
        "agua_g": 73,
        "vitamina_c_mg": 10,
        "vitamina_a_ug": 7,
        "potassio_mg": 485,
        "calcio_mg": 12,
        "ferro_mg": 0.6,
        "alergias": ["FRUTAS"],
        "descricao": "Cremoso e cheio de gorduras boas — ótimo em tostas ou saladas. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Queijo fresco (cottage)",
        "energia_kcal": 98,
        "proteina_g": 11.1,
        "hidratos_g": 3.4,
        "acucares_g": 2.7,
        "lipidos_g": 4.3,
        "agua_g": 79,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 27,
        "potassio_mg": 104,
        "calcio_mg": 83,
        "ferro_mg": 0.2,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Leve e proteico — ótimo em sandes e snacks. Aconselhável (verde).",
        "cor": "verde"
    },
    {
        "nome": "Queijo mozzarella",
        "energia_kcal": 280,
        "proteina_g": 22.0,
        "hidratos_g": 2.2,
        "acucares_g": 1.0,
        "lipidos_g": 17.0,
        "agua_g": 51,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 360,
        "potassio_mg": 133,
        "calcio_mg": 505,
        "ferro_mg": 0.3,
        "alergias": ["LEITE_DERIVADOS"],
        "descricao": "Fresco e ótimo em pizzas e saladas — fonte de proteína. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Fiambre|Presunto cozido",
        "energia_kcal": 145,
        "proteina_g": 20,
        "hidratos_g": 1.5,
        "acucares_g": 1.0,
        "lipidos_g": 6.5,
        "agua_g": 70,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 5,
        "potassio_mg": 300,
        "calcio_mg": 10,
        "ferro_mg": 0.9,
        "alergias": [],
        "descricao": "Fonte rápida de proteína, mas contém sal. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Bacon (frito)",
        "energia_kcal": 541,
        "proteina_g": 37,
        "hidratos_g": 1.4,
        "acucares_g": 0.0,
        "lipidos_g": 42,
        "agua_g": 8,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 20,
        "potassio_mg": 565,
        "calcio_mg": 10,
        "ferro_mg": 2.2,
        "alergias": [],
        "descricao": "Muito saboroso mas gorduroso e salgado. Pouco aconselhável (laranja) — reserva para ocasiões.",
        "cor": "laranja"
    },
    {
        "nome": "Salmão fumado",
        "energia_kcal": 117,
        "proteina_g": 18,
        "hidratos_g": 0,
        "acucares_g": 0,
        "lipidos_g": 4.4,
        "agua_g": 67,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 50,
        "potassio_mg": 300,
        "calcio_mg": 11,
        "ferro_mg": 0.8,
        "alergias": ["PEIXES"],
        "descricao": "Fonte de ômega-3 e proteína; sabor forte. Aconselhável com moderação (amarelo).",
        "cor": "amarelo"
    },
    {
        "nome": "Ovo cozido (sem casca)",
        "energia_kcal": 155,
        "proteina_g": 13,
        "hidratos_g": 1.1,
        "acucares_g": 1.1,
        "lipidos_g": 11,
        "agua_g": 75,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 140,
        "potassio_mg": 126,
        "calcio_mg": 50,
        "ferro_mg": 1.2,
        "alergias": ["OVOS"],
        "descricao": "Cheio de proteína — ótimo para saciar. Aconselhável (verde) com regularidade.",
        "cor": "verde"
    },
    {
        "nome": "Ovo estrelado (frito)",
        "energia_kcal": 196,
        "proteina_g": 13,
        "hidratos_g": 1.1,
        "acucares_g": 1.1,
        "lipidos_g": 15,
        "agua_g": 69,
        "vitamina_c_mg": 0,
        "vitamina_a_ug": 140,
        "potassio_mg": 126,
        "calcio_mg": 50,
        "ferro_mg": 1.2,
        "alergias": ["OVOS"],
        "descricao": "Gosto bom mas tem mais gordura por fritura. Comer com moderação — (amarelo).",
        "cor": "amarelo"
    }
]
