# pequeno_almoco.py
pequeno_almoco_nomes = [
    "Maçã",
    "Banana",
    "Laranja (fruta)",
    "Sumo de laranja (natural)",
    "Sumo de maçã (natural)",
    "Morangos",
    "Framboesa",
    "Kiwi",
    "Pera",
    "Leite integral",
    "Leite magro",
    "Leite de amêndoa (sem açúcar, comercial)",
    "Leite de soja (sem açúcar)",
    "Iogurte natural (inteiro)",
    "Iogurte grego (integral)",
    "Café preto (sem açúcar)",
    "Chá preto (preparado)",
    "Café com leite",
    "Chocolate quente (com leite)",
    "Smoothie de morango (média)",
    "Aveia (flocos, seca)",
    "Papas de aveia (cozidas)",
    "Cereal instantâneo de aveia (preparado)",
    "Cereais flocos (cornflakes)",
    "Granola (com FRUTAS secos e mel)",
    "Muesli (sem açúcar)",
    "Pão integral",
    "Pão branco",
    "Bagel (simples)",
    "Bagel integral com sementes",
    "Croissant",
    "Torrada com tomate (preparado)",
    "Panquecas (cozidas, simples)",
    "Panqueca de aveia com banana",
    "Crepe simples",
    "Waffle",
    "Muffin de mirtilo",
    "Xarope de bordo (maple syrup)",
    "Mel (apicultura)",
    "Manteiga (normal)",
    "Manteiga de amendoim (cremosa)",
    "Nozes (mistura: noz, amêndoa, avelã) — FRUTAS secos",
    "Amêndoas cruas",
    "Amendoim torrado sem sal",
    "Sementes de chia",
    "Abacate",
    "Queijo fresco (cottage)",
    "Queijo mozzarella",
    "Fiambre|Presunto cozido",
    "Bacon (frito)",
    "Salmão fumado",
    "Ovo cozido (sem casca)",
    "Ovo estrelado (frito)"
]